'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CodilloComprog.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property adobo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adobo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property adobo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adobo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property adobo2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("adobo2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Almond_Cherry_Smoothie() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Almond_Cherry_Smoothie", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Arista() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Arista", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Avocado_Coconut_Smoothie() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Avocado_Coconut_Smoothie", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property backgrouunddessert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backgrouunddessert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property backgroynddrinks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backgroynddrinks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property backgroyndfoods() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backgroyndfoods", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property baked_mac__1_() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("baked_mac__1_", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bakery() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bakery", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Banana_Smoothie() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Banana_Smoothie", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Basil_Pork_Belly() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Basil_Pork_Belly", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property beef_kushiyaki() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("beef_kushiyaki", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property beef_rolls() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("beef_rolls", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Beef_with__Broccoli() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Beef_with__Broccoli", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property beef_yakitori() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("beef_yakitori", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property bicol_express() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("bicol_express", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Bistek() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Bistek", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property black_forest() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("black_forest", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property black_forest__1_() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("black_forest__1_", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Bossam() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Bossam", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property brownies() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("brownies", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bubble_tea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bubble-tea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property bulgogi() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("bulgogi", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property bulgogi1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("bulgogi1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property butamaki() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("butamaki", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property caesar() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("caesar", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cake() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cake", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property caramel_bar() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("caramel_bar", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property carbonara() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("carbonara", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Carrot_Cake() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Carrot_Cake", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Carrot_Juice() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Carrot_Juice", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chef_Hat_cooking_logo_template_removebg_preview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chef_Hat_cooking_logo_template-removebg-preview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property chickadobo() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("chickadobo", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property chickafritada() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("chickafritada", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chicken() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chicken", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property chicken_alfredo() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("chicken_alfredo", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chicken_curry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chicken curry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property chicken_florentine() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("chicken_florentine", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chicken_leg___Copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chicken-leg - Copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chicken_tempura() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chicken tempura", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chicken_teriyaki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chicken teriyaki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property chocolate() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("chocolate", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Chocolate_Cake() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Chocolate_Cake", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property chopseuy() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("chopseuy", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property coffee_crumble() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("coffee_crumble", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property cookies() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("cookies", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property cookies_and__cream() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("cookies_and__cream", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property CookUp() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("CookUp", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property cumin_crusted_porkchops() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("cumin_crusted_porkchops", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property curry() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("curry", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property curry__1_() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("curry__1_", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cutlery() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cutlery", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cutlery1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cutlery1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dessert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dessert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property dol_sot_bi_bim_bap() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dol_sot_bi_bim_bap", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Dragon_fruit_Smoothie() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Dragon_fruit_Smoothie", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property drink() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("drink", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property dukkah_spiced_porkchops() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dukkah_spiced_porkchops", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property dwaeji_galbi() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dwaeji_galbi", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property fatteh() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("fatteh", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property foods() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("foods", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property fried_kangkong() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("fried_kangkong", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property galbi() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("galbi", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Garlic_Pepper_pork() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Garlic_Pepper_pork", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property grilled_beef_short_ribs() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("grilled_beef_short_ribs", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property gyoza() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("gyoza", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Harissa_Porkchop() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Harissa_Porkchop", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ice_cream() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ice-cream", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_beef_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-beef-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_ellipsis_90() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-ellipsis-90", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_meat_100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-meat-100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property italian_amrican() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("italian-amrican", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property italian_amrican1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("italian-amrican1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property japanese_chicken() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("japanese chicken", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property japchae() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("japchae", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property jeyuk_bokkeum() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("jeyuk_bokkeum", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property jokbal() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("jokbal", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property kakuni() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("kakuni", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property kalbi() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("kalbi", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Kaldereta() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Kaldereta", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property kaldereta1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("kaldereta1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Kao_moo_dang() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Kao_moo_dang", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property karaage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("karaage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property karaage1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("karaage1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property kare_kare() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("kare_kare", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property kebab() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("kebab", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property korean_style_chicken() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("korean style chicken", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property larb() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("larb", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property lasagna() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("lasagna", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property lechon_kawali() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("lechon_kawali", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Lemon_Juice() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Lemon_Juice", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property list() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("list", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property macaroni_salad() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("macaroni_salad", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property maiale_ubriaco() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("maiale_ubriaco", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property mandi() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("mandi", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property mango() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("mango", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property mango_cake() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("mango_cake", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property mansaf() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("mansaf", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property marsala() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("marsala", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Mechado() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Mechado", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property menudo() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("menudo", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property middle_east_chicken() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("middle east chicken", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property minced_beef() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("minced_beef", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property moo_ping() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("moo_ping", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Morcon() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Morcon", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property nikujaga() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("nikujaga", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Nilaga() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Nilaga", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Orange_Juice1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Orange_Juice1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property oyakodon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oyakodon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property oyakodon1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("oyakodon1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property pad_kra_pao() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("pad_kra_pao", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property pad_thai() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("pad_thai", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property pampanella() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("pampanella", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property parmesan() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("parmesan", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property people() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("people", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property piccata() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("piccata", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Pineapple_Smoothie() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Pineapple_Smoothie", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Pineapple_Vodka_Cocktail() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Pineapple_Vodka_Cocktail", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Porchetta() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Porchetta", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Pork_and_persimmon() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Pork_and_persimmon", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Pork_involtini() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Pork_involtini", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Pork_Lombardy() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Pork_Lombardy", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property pork_steak() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("pork_steak", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Raspberry_Lime_Vodka_Cocktail() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Raspberry_Lime_Vodka_Cocktail", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property satay() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("satay", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property shawarma() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("shawarma", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property shogayaki() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("shogayaki", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property sinigang() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("sinigang", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property smoothie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smoothie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property spag() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("spag", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property spaguetti() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spaguetti", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property strawberry() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("strawberry", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Strawberry_Cake() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Strawberry_Cake", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Strawberry_Smoothie() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Strawberry_Smoothie", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property sukiyaki() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("sukiyaki", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property suyuk() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("suyuk", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property tahini_dressed_pork() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("tahini_dressed_pork", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property tempura() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("tempura", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Teriyaki() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Teriyaki", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property thai_style_chicken() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("thai style chicken", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property tinola() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("tinola", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property tom_kha_gai() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("tom_kha_gai", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property tom_yum() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("tom_yum", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property tonkatsu() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("tonkatsu", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property tuna_pasta() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("tuna_pasta", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ube_cake() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ube_cake", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property vanilla() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("vanilla", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vegetables() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vegetables", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property water_glass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water-glass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Watermelon_Tequila_Cocktail() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Watermelon_Tequila_Cocktail", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wine_bottle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wine-bottle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property yakiton() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("yakiton", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property yakitori() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yakitori", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property yakitori1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("yakitori1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Za_atar_Pork_Tenderloin() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Za_atar_Pork_Tenderloin", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
